apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: define-ansible-job-template
  title: Ansible Job Template
  description: Define an Ansible Job Template within Ansible Automation Platform
  tags:
    - recommended
    - aap
spec:
  owner: janus-authors
  system: janus-idp
  type: service
  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
        - repoName
        - owner
        - system
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
        owner:
          title: Owner
          type: string
          description: Owner of the component
        repoName:
          title: Repository Name
          type: string
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
    - title: Ansible Job Definition
      required:
        - name
        - description
        - namespace
        - inventory
        - project
        - playbook
        - ask_vars_on_launch
        - credential
        - connection_secret
        - vm_name
        - vm_template_from
        - vm_library
        - vm_cpus
        - vm_memory
      properties:
        name:
          title: Name of the Ansible Job Template
          type: string
          description: A unique name for the Ansible Job Template
        playbook:
          title: Ansible Playbook
          type: string
          description: Specify an Ansible Playbook to run
        description:
          title: Description
          type: string
          description: Provide a description of the Job Template to be defined
        namespace:
          title: Namespace
          type: string
          description: Specify the namespace to launch the job
          default: aap
        inventory:
          title: Inventory
          type: string
          description: Specify the inventory to use for the job
          default: aap
        project:
          title: Project
          type: string
          description: Specify the Ansible Project to use for the job
          default: aap
        credential:
          title: Credential
          type: array
          description: Specify the credential to use for the job
          items:
            type: string
            enum:
              - CentOS root
              - VEGA-VCenter
          uniqueItems: true
          ui:widget: checkboxes
        connection_secret:
          title: Connection Secret
          type: string
          description: Specify the connection secret to use for the job
          default: aapaccess
        vm_name:
          title: Name of Vm
          type: string
          description: Vm name to be create
        vm_template_from:
          title: Source template for Vm
          type: string
          default: CentOS7
          enum:
            - CentOS7
          enumNames:
            - "CentOS7"
        vm_library:
          title: Library template for Vm
          type: string
          default: Crif-PoC
          enum:
            - Crif-PoC
          enumNames:
            - "Crif-PoC"
        vm_cpus:
          title: Override VM cpus numbers
          type: string
        vm_memory:
          title: Override VM RAM (in MB)
          type: string
        extra_vars:
          title: Extra Vars
          type: string
          description: Specify any extra vars to use for the job template
          ui:widget: textarea
          ui:options:
            rows: 15
        ask_vars_on_launch:
          title: Ask Vars on Launch
          type: boolean
          description: Specify whether to ask for extra vars on launch
          default: false
  steps:
    - id: template
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: argo/ansibleJobTemplates/
        values:
          component_id: ${{ parameters.name }}
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          inventory: ${{ parameters.inventory }}
          credential: ${{ parameters.credential }}
          project: ${{ parameters.project }}
          playbook: ${{ parameters.playbook }}
          connection_secret: ${{ parameters.connection_secret }}
          vm_name: ${{ parameters.vm_name }}
          vm_template_from: ${{ parameters.vm_template_from }}
          vm_library: ${{ parameters.vm_library }}
          vm_cpus: ${{ parameters.vm_cpus }}
          vm_memory: ${{ parameters.vm_memory }}
          extra_vars: 
            ${{ parameters.extra_vars }}
          ask_vars_on_launch: ${{ parameters.ask_vars_on_launch }}

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../skeletons/catalog-info/
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          applicationType: api
          description: ${{ parameters.description }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is a test
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}
        repoVisibility: public
        defaultBranch: main
        gitCommitMessage: "feat(all): first commit"

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}