---
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: ${{ values.name }}-job-template
  namespace: ${{ values.namespace }}
spec:
  tower_auth_secret: ${{ values.connection_secret }}
  job_template_name: ${{ values.name }}
  job_template_project: ${{ values.project }}
  ask_variables_on_launch: ${{ values.ask_vars_on_launch }}
  job_template_playbook: ${{ values.playbook }}
  job_template_inventory: ${{ values.inventory }}
  job_template_credentials: [${{ values.credential }}]
  job_template_extra_vars:
    vm_name: ${{ values.vm_name }}
    vm_template_from: ${{ values.vm_template_from }}
    vm_library: ${{ values.vm_library }}
    vm_cpus: ${{ values.vm_cpus }}
    vm_memory: ${{ values.vm_memory }}    
    ${{ values.extra_vars }}